### ISSUE TITLE
Add to list of drivers

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/ssd1306#1]
Open a PR to add this crate to the [list of drivers](https://github.com/japaric/embedded-hal#drivers) when it's ready.

**Comment by therealprof** [comment]
I can certainly help with that.

**Comment by jamwaffles** [comment]
Thanks! There's also [the weekly driver initiative](https://github.com/rust-lang-nursery/embedded-wg/issues/39). Should it be added to both?

**Comment by therealprof** [comment]
The plan is to concentrate all the different sites and places in one so the information is not as scattered. https://github.com/rust-lang-nursery/embedded-wg/issues/68

**Comment by therealprof** [comment]
Just let me know when you'd like to have this added. We can already do so now as [WIP] item.

**Comment by jamwaffles** [comment]
WIP is fine for now! I don't think we're that far off a 0.1 release in terms of features but there's quite a lot of doc/blog post writing before removing the WIP flag.

**Comment by jamwaffles** [comment]
We're [here](https://github.com/rust-embedded/awesome-embedded-rust#wip) now 😄
