### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by invis87** [jamwaffles/ssd1306#102]
- Version of `ssd1306` in use (if applicable): master branch (or "v0.3.0-alpha.2")

## Description of the problem/feature request/other
Fail to compile this project because `embedded-graphics` removed `Drawing` trait. 
```
cargo build  --example image_i2c
   Compiling ssd1306 v0.3.0-alpha.2 (/Users/pronvis/rust/xxx/ssd1306)
error[E0432]: unresolved import `self::embedded_graphics::Drawing`
   --> src/mode/graphics.rs:267:5
    |
267 |     Drawing,
    |     ^^^^^^^ no `Drawing` in the root
```

**Comment by jamwaffles** [comment]
Thanks for reporting this. It's now fixed and released in [0.3.0-alpha.3](https://crates.io/crates/ssd1306/0.3.0-alpha.3).

**Comment by invis87** [comment]
Wow... interesting fix))) Thanks!

**Comment by jamwaffles** [comment]
No problem! Apologies for the breakage
