### ISSUE TITLE
Incorrect min_y?

### ISSUE THREAD

**Issue by bugadani** [jamwaffles/ssd1306#122]
Based on [this metric](http://reviewthecode.blogspot.com/2016/01/wtf-per-minute-actual-measurement-for.html) I believe the linked line may be incorrect.

https://github.com/jamwaffles/ssd1306/blob/96170fd21419e73fdb2299f395b07836d52d090f/src/mode/graphics.rs#L161

If that's supposed to be height, I'm happy to fix it, otherwise please provide an explanation why it's width.

**Comment by jamwaffles** [comment]
Yeah that definitely looks like it should be `height - 1`. There's a similar block of code [here](https://github.com/jamwaffles/ssd1306/blob/96170fd21419e73fdb2299f395b07836d52d090f/src/mode/graphics.rs#L111-L114), so it might be worth moving the min/max reset into a private method.

**Comment by bugadani** [comment]
I haven't given it much thought, but shouldn't these be rotation aware values? Is min_y the same when rotated by 90 or 270 degrees?

**Comment by therealprof** [comment]
Yes, there're the other variables which take the rotation into account. However it's a bit weird to have the manual comparison in the code. There're `max()` and `min()` functions for that.

**Comment by bugadani** [comment]
> There's a similar block of code [here](https://github.com/jamwaffles/ssd1306/blob/96170fd21419e73fdb2299f395b07836d52d090f/src/mode/graphics.rs#L111-L114), so it might be worth moving the min/max reset into a private method.

You mislead me :) That block is marking the whole display to be updated, the original block resets the area to nothing.

**Comment by jamwaffles** [comment]
Oop yes you're right, min/max are swapped there. My bad!
