### ISSUE TITLE
Incomplete bounds check in set_pixel

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/ssd1306#151]
- Version of `ssd1306` in use (if applicable): `master`
- Display resolution and interface: I2C, 128x32

## Description of the problem

The bounds check in `GraphicsMode::set_pixel` is incomplete, which causes overdraw on the right side of the display to be wrapped around to the left side.

## Test case (if applicable)

```rust
 let style = PrimitiveStyleBuilder::new()
    .stroke_width(1)
    .stroke_color(BinaryColor::On)
    .build();

Circle::new(Point::new(128, 16), 8)
    .into_styled(style)
    .draw(&mut disp)
    .unwrap();
```

![grafik](https://user-images.githubusercontent.com/226123/114588932-7e650600-9c87-11eb-9fd5-8021551d293e.png)

**Comment by jamwaffles** [comment]
This now uses the `bounding_box().contains()` method from e-g 0.7. Untested, but closed by #154 nonetheless.
