### ISSUE TITLE
Release blog post

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/ssd1306#18]
I've got a blog at [wapl.es](http://wapl.es) (repo [here](https://github.com/jamwaffles/jamwaffles.github.io)) which would be a good home for a release blog post. Would anybody like to write/host one? If not, I'll write it and tag @scowcron and @therealprof in a PR.

**Comment by therealprof** [comment]
To many construction sites on my end at the moment, I'm afraid.

**Comment by jamwaffles** [comment]
[Kool](https://wapl.es/electronics/rust/2018/04/30/ssd1306-driver.html)
