### ISSUE TITLE
Travis should check other targets than just variants of ARM-M

### ISSUE THREAD

**Issue by therealprof** [jamwaffles/ssd1306#32]
There's IMHO not to much point in testing 4 variants of ARM-M which only differ in minor aspects. Maybe throw in a `std` target and a different `no_std` one for good measure instead?

**Comment by jamwaffles** [comment]
Any idea how to fix [this `eh_personality` issue](https://travis-ci.org/jamwaffles/ssd1306/jobs/360676186)? I've randomly added a couple of new targets. Not sure if they're the right ones.
