### ISSUE TITLE
Fix duplicate buffer in I2C code

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/ssd1306#6]
[`send_data()`](https://github.com/jamwaffles/ssd1306/blob/master/src/interface/i2c.rs#L28-L40) should be using less memory. @scowcron's [implementation](https://github.com/EdgewaterDevelopment/rust-ssd1306/blob/master/src/prelude.rs#L27) uses buffered chunks which might be a good way to go. Adding the initial `0x40` to the beginning of the buffer makes using another buffer a necessity at the moment.

**Comment by scowcron** [comment]
relevant, I think: https://github.com/japaric/embedded-hal/pull/47

**Comment by jamwaffles** [comment]
That looks good. Until that gets merged/implemented though, I think the best way to go is to port over your chunked tx buffer idea. 17 bytes isn't much, even for a uC.
