### ISSUE TITLE
Travis?

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/ssd1306#7]
We should have some kind of CI process!

At minimum, right now I think it should:

- Run `rustfmt` and fail if any code changes to keep code clean and consistent
- Run `cargo test` to make sure the examples build*

*<sub>because there aren't any tests at the moment...</sub>

Anything else?

**Comment by scowcron** [comment]
Docs would be nice. take a look at `cargo doc-upload`. I did some fiddling with it here:

https://github.com/EdgewaterDevelopment/rust-ssd1306/blob/master/.travis.yml

**Comment by jamwaffles** [comment]
I like that. Is there a way to get it to upload to docs.rs? I can't decide whether using docs.rs or GitHub pages is better at the moment.

**Comment by scowcron** [comment]
I've never worked with docs.rs, from what I read doc-upload just updates and pushes to your gh-pages branch. the other thing that might be worth looking at is japaric's trust repo, I didn't really dig into it, but it looks kind of nifty.

**Comment by jamwaffles** [comment]
Hmm, at first glance it looks like overkill for this crate at the moment at least. Tbf, pushing to a gh-pages branch gives us more control anyway so it's not such a bad thing.

**Comment by jamwaffles** [comment]
Closed by #29
