### ISSUE TITLE
Re: latest build errors

### ISSUE THREAD

**Issue by chocol4te** [jamwaffles/ssd1306#70]
I'm having the exact same issue with a lot of my projects. It's due to crates using an outdated version of `proc-macro2`. Most use 0.3.8 but the issues are fixed on the latest. I think the solution is a whole lot of PRs with the latest version, but its hard to replicate locally (each broken crate requires cloning then making dependancies point to a local directory).

**Comment by jamwaffles** [comment]
Yeah, I see the failed daily build all the time :). I had a look at fixing the cortex-m-rtfm-macros crate which is where I think the error lies but gave up. I'm kinda just sitting around waiting for @japaric to fix it ;)

**Comment by chocol4te** [comment]
I've made some PRs which should fix everything once merged. :)

**Comment by jamwaffles** [comment]
[This one](https://github.com/japaric/cortex-m-rtfm/pull/80) and [this one](https://github.com/japaric/rtfm-syntax/pull/8)? Can't wait! Would be great to have this driver building again.
