### ISSUE TITLE
Enhancement: Support sh1106 chip as well as ssd1306

### ISSUE THREAD

**Issue by nickbroon** [jamwaffles/ssd1306#75]
Would it be easy to extend this driver to also support the ssh1106 oled driver chip?
The ssh1106 is very similar to the ssd1306 being popular of [raspberry pi breakouts](https://shop.pimoroni.com/products/1-12-oled-breakout).
There are several C and python driver libraries that support both:
https://github.com/durydevelop/arduino-lib-oled
https://luma-oled.readthedocs.io/en/latest/

**Comment by jamwaffles** [comment]
I've been meaning to write a driver for the SSH1106 actually. This driver is specifically for the SSD1306 and, while there might be some overlap with other drivers, it seems the pattern in the community right now is to have a crate specialised to each driver chip so that would be the way to go.

**Comment by therealprof** [comment]
Well, the SSH1106 has internal memory which can also be accessed so there's the option to read back the framebuffer instead of using a lot of MCU RAM to hold it which probably requires a different design.

**Comment by jamwaffles** [comment]
This issue has spurred me to create https://github.com/jamwaffles/sh1106. It's a copy of this repo with some renames. I've managed to get some snow and a small bit of the demos (`cargo run --example terminal_i2c` is good for testing), but not a complete image. The commands look similar/the same, but the way the display is written to seems to require manual shifting of pages as opposed to the SSD1306' automatic increments. It would be great to have some help on that repo!

**Comment by nickbroon** [comment]
I'll try and find some time this week to give the demo a run, and read over the datasheet.

**Comment by jamwaffles** [comment]
The [sh1106 crate](https://crates.io/crates/sh1106) is now published! Well, a little while ago actually...

It's a little rough so please give it a test and report any bugs you find.
