### ISSUE TITLE
Building examples fails due to deprecated digital::OutputPin

### ISSUE THREAD

**Issue by BenBergman** [jamwaffles/ssd1306#81]
I just tried to build the examples using a fresh clone of the repo and got a number of errors (escalated from warnings due to https://github.com/jamwaffles/ssd1306/blob/master/src/lib.rs#L160)

```
error: use of deprecated item 'hal::digital::OutputPin::set_low': Deprecated because the methods cannot return errors. Users should use the traits in digital::v2.
```

It sounds like the solution is to just update to the latest traits, so I did that in my local copy and got the examples to build. I can create a PR, but right now I'm just throwing away the result from the pin state changes (which I guess effectively matches the existing behaviour). If more thorough error handling seems appropriate I'm open to that.

**Comment by jamwaffles** [comment]
Fixed in #83
