### ISSUE TITLE
TerminalMode 90 and 270 degree rotations incorrect

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/ssd1306#85]
As reported in #47.

In `TerminalMode`, the text isn't rotated properly in these two rotations. Instead, it's just drawn backwards for 90 degrees:

![IMG_20190701_212612](https://user-images.githubusercontent.com/800791/60464839-833dfe80-9c47-11e9-9f74-43ab06b0cc7c.jpg)

And like this for 270 degrees:

![IMG_20190701_212641](https://user-images.githubusercontent.com/800791/60464848-8e912a00-9c47-11e9-9210-9ee4683fc071.jpg)

0 and 180 degrees work fine.

**Comment by bugadani** [comment]
Are graphics mode rotations correct? As far as I can tell by looking at the code, only the x and y coordinates are flipped, so I think the displayed image is horizontally flipped?

**Comment by jamwaffles** [comment]
Closed by #129 I believe.
